### ISSUE TITLE
Please update your documentation for Play 2.3 and its activator installation

### ISSUE THREAD

**Issue by doliver3** [scala-ide/scala-ide-play2#223] opened 2014-09-01 16:08 UTC
Hi,

The Play 2.3 activator installation instructions no longer appear to be in agreement with this plugin. Play is now using Activator as their primary distribution mechanism. 

When do you expect that this scala-ide plugin will work with Play 2.3?

Thanks,
David

**Comment by benmccann** [comment] 2015-03-12 07:32
Should we update the README to not refer to Play 2.1 then?

**Comment by dotta** [comment] 2015-05-11 12:47
If this issue was about updating our README and wiki, then it can be closed as a duplicate of #243.

@doliver3 I'm going to close this ticket as I assume the confusion was due to lack of documentation. If that isn't the case, please feel free to reopen this ticket.

**Closed by dotta** 2015-05-11 12:47 UTC
