### ISSUE TITLE
The import views.html.index cannot be resolved

### ISSUE THREAD

**Issue by mundadasuraj** [scala-ide/scala-ide-play2#215] opened 2014-07-13 11:43 UTC
Hi,

My config is

activator : 1.2.3
Java to Scala Plugin: 1.2.0.v-2_10-201404011311-48c58ab
Java EE IDE: 2.0.2.20140224-0000
Play 2 Support: 0.4.3.v-2_10-201403271612-2a1df2b
Scala IDE : 3.0.3.v-2_10-201403271605-8d2c756

I am testing HelloWorld projects in Eclipse and getting following error in Application.java

1. The import views.html.index cannot be resolved
2. index cannot be resolved

I looked on web and many have faced this issue. Some suggested running the example through play console and then refresh the Eclipse project. I tried it without any success.

The code compiles and run fine in activator ui. Its the issue with Eclipse Scala IDE or Play plugin.

**Comment by urquilla** [comment] 2015-02-10 23:20
+1 

>My workaround to fix it:
>1. activator clean eclipse
>2. refresh the project in eclipse

This worked perfectly, thanks.

**Comment by TigranTsat** [comment] 2015-10-10 22:55
That what helped me - `activator clean compile eclipse`

**Comment by mkurz** [comment] 2015-10-10 23:58
This should be fixed with Play 2.4 and sbt-eclipse plugin version 4.

**Comment by sschaef** [comment] 2015-10-11 08:01
What did they change? Wasn't the generated code on the classpath in earlier versions?

**Comment by mkurz** [comment] 2015-10-12 11:13
@sschaef It looks like sbt-eclipse prior version 4.0 was just broken. I don't know exactly what, but a lot of work has been put into 4.0 - and it's working now.

**Comment by sschaef** [comment] 2015-10-12 13:41
Ok, I close this then.

**Closed by sschaef** 2015-10-12 13:41 UTC

**Comment by venkatsalem** [comment] 2015-10-31 22:32
I had similar issue. I added /target/scala-2.1.1/classes into Libraries -> Add Class Folder to resolve this issue.

**Comment by hnmg** [comment] 2015-12-20 21:24
venkatsalem, thanks. This workaround is the only one that worked for me.

**Comment by CharlesOy** [comment] 2016-07-26 00:26
@peter-fu Thanks, you made my day.

**Comment by peter-fu** [comment] 2016-07-27 02:14
@CharlesOy Glad it helped!

And I agree with @mkurz, would recommend upgrade to [Play](https://www.playframework.com/download) 2.4+ with [sbteclipse](https://github.com/typesafehub/sbteclipse) 4.0.0, the problem is gone totally.

**Comment by mkurz** [comment] 2017-01-13 11:36
This is finally completely solved:
Upgrade `sbteclipse` to version `5.1.0` (which was released on January 12th 2017) - it fixes this bug. See https://github.com/typesafehub/sbteclipse/pull/328

**Comment by muizidn** [comment] 2018-12-26 04:25
I am using Play 2.6.20 and sbteclipse 5.2.2 but the error still exist. The app runs fine in browser though. I am using VSCode.
